version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - '5440:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  full-back:
    build:
      context: .
    environment:
      SERVER_PORT: 8500
    depends_on:
      - postgres
    ports:
      - '8500:8500'
        
volumes:
  postgres-volume: